return {
	hp = "Icon_HP.png",
	firepower = "Icon_Gun.png",
	armor = "Icon_Armor.png",
	torpedo = "Icon_Torpedo.png",
	evasion = "Icon_Evasion.png",
	aa = "Icon_AA.png",
	aircraft = "Icon_Aircraft.png",
	asw = "Icon_ASW.png",
	speed = "Icon_Speed.png",
	los = "Icon_LOS.png",
	range = "Icon_Range.png",
	luck = "Icon_Luck.png",
	bombing = "Icon_Dive.png",
	shelling_accuracy = "Icon_Hit.png",
	anti_bomber = "Icon_Hit.png",
	interception = "Icon_Evasion.png",
	combat_radius = "Icon_Range.png",
}